/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khoj_AI;
import java.sql.*;
import java.util.Arrays;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
/**
 *
 * @author DELL
 */
public class Registration extends javax.swing.JFrame {
    Connection myConn = null;
        Statement myStmt = null;
        ResultSet myRs = null;

        String user = "root";
        String pass = "HelpPls2";

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        this.setSize(600, 650);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderButtonGroup = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Username = new javax.swing.JTextField();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jComboBox3 = new javax.swing.JComboBox<String>();
        jButton1 = new javax.swing.JButton();
        Pass1 = new javax.swing.JPasswordField();
        Pass2 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));
        setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setText("Name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 173, 40, 19);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setText("Username:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 258, 68, 19);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 346, 65, 19);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setText("Confirm Password:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 390, 118, 19);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setText("Gender:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 434, 52, 19);
        getContentPane().add(Name);
        Name.setBounds(339, 166, 193, 26);
        getContentPane().add(Username);
        Username.setBounds(339, 254, 193, 26);

        GenderButtonGroup.add(Male);
        Male.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Male.setText("Male");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });
        getContentPane().add(Male);
        Male.setBounds(339, 430, 59, 29);

        GenderButtonGroup.add(Female);
        Female.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Female.setText("Female");
        getContentPane().add(Female);
        Female.setBounds(416, 430, 75, 29);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setText("DateOfBirth:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 481, 78, 19);

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox1.setSelectedIndex(8);
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(339, 481, 40, 21);

        jComboBox2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jComboBox2.setSelectedIndex(10);
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(397, 481, 98, 21);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019" }));
        jComboBox3.setSelectedIndex(39);
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(513, 477, 68, 26);

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(265, 565, 71, 25);
        getContentPane().add(Pass1);
        Pass1.setBounds(339, 342, 193, 26);
        getContentPane().add(Pass2);
        Pass2.setBounds(339, 386, 193, 26);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel7.setText("Email:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 302, 38, 19);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setText("Address:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 525, 56, 19);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(339, 298, 193, 26);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(339, 521, 193, 26);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setText("Contact No.:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 217, 78, 19);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(339, 210, 193, 26);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Registration");
        
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\Niraj\\Desktop\\object-recognition-tensorflow-master\\object-recognition-tensorflow-master\\src\\main\\java\\image_s\\Webp.net-resizeimage.png");
       

        jLabel12.setIcon(imageIcon); // NOI18N
        //jLabel12.setText("jLabel12");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 610, 130);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 130, 610, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        char[] a=new char[50];
        char[] b=new char[50];
        String cn,password="";
        String c;
        String d;
        String addr;
        String regex = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        addr=jTextField2.getText();
        String email1=jTextField1.getText();            
        cn=jTextField3.getText();
        a=Pass1.getPassword();
        b=Pass2.getPassword();
        
        c=Name.getText();
        d=Username.getText();
        boolean a1=true; // to check if password and confirm password match
        boolean a2=true; // to check if name is empty
        boolean a3=true; // to check if username is empty
        boolean a4=true; // to check if male is selected
        boolean a5=true; // for checking if female is selected
        boolean a6=true; // to check of contact number is 10
        boolean a7=true; // for checking contact number is all numbers
        boolean a8=true; // for checking address field is not empty
        boolean a9=true; // to check if email is in valid format
        if(addr.isEmpty())
        {
            a8=false;
        }
        if(!(email1.matches(regex)))
            a9=false;
        //code to assign value to a7
        try{
            Double num=Double.parseDouble(cn);
        }
        catch(NumberFormatException e){
            a7=false;
        }
        a4=Male.isSelected();
        a5=Female.isSelected();
        //All stuff done below to prepare for calculation of age
        final Calendar calendar=Calendar.getInstance();
        int day1=calendar.get(Calendar.DAY_OF_MONTH);
        int year1=calendar.get(Calendar.YEAR);
        int month1= calendar.get(Calendar.MONTH) + 1;
        int day=jComboBox1.getSelectedIndex()+1;
        int month=jComboBox2.getSelectedIndex()+1;
        int year=jComboBox3.getSelectedIndex()+1980;
        int yeard,monthd,dayd;
        yeard=year1-year;
        monthd=month1-month;
        dayd=day1-day;
        //calculation of age below
        int age=0;
        if(yeard==0)
            age=0;
        else if(yeard>0&&monthd>0)
        {
            age=yeard;
        }
        else if(yeard>0&&monthd==0&&dayd>=0)
        {
            age=yeard;
        }
        else if(yeard>0&&monthd==0&&dayd<0)
        {
            age=yeard-1;
        }
        //calculation of age finished
        if(cn.length()!=10)
        {
         a6=false;   
        }
        if(c.isEmpty())
        {
         a2=false;   
        }
        if(d.isEmpty())
        {
            a3=false;
        }
        if(Arrays.equals(a, b))
        {
            a1 = true;
            password = String.valueOf(a);
        }
        else
        {
            a1=false;
        }
        if(a1&&a2&&a3&&(a4||a5)&&a6&&a7&&a8&&a9)
        {
         JOptionPane.showMessageDialog(this,"Registered Succesfully","Congratulations",JOptionPane.PLAIN_MESSAGE);  
         //JOptionPane.showMessageDialog(this,day+"/"+month+"/"+year,"Congratulations",JOptionPane.ERROR_MESSAGE);
         dispose();
        }
        else if(a2&&a3&&!a1)
        {
         JOptionPane.showMessageDialog(this,"Passwords don't Match","Alert",JOptionPane.ERROR_MESSAGE);
        }
        else if(a1&&a2&&(a4||a5)&&a6&&a7&&a8&&a9&&!a3)
        {
         JOptionPane.showMessageDialog(this,"Username cannot be empty","Alert",JOptionPane.ERROR_MESSAGE);
        }
        else if(a1&&a3&&(a4||a5)&&a6&&a7&&a8&&a9&&!a2)
        {
         JOptionPane.showMessageDialog(this,"Name cannot be empty","Alert",JOptionPane.ERROR_MESSAGE);
        }
        else if(!a4&&!a5&&a1&&a2&&a3&&a6&&a7&&a8&&a9)
        {
         JOptionPane.showMessageDialog(this,"Select a Gender","Alert",JOptionPane.ERROR_MESSAGE);   
        }
        else if(a1&&a2&&a3&&(a4||a5)&&a8&&a9&&(!a6))
        {
         JOptionPane.showMessageDialog(this,"Contact No. should be of 10 digits","Alert",JOptionPane.ERROR_MESSAGE);      
        }
        else if(a1&&a2&&a3&&(a4||a5)&&a6&&a8&&a9&&(!a7))
        {
         JOptionPane.showMessageDialog(this,"Contact No. can be only numeric","Alert",JOptionPane.ERROR_MESSAGE);     
        }
        else if(a1&&a2&&a3&&(a4||a5)&&a6&&a7&&a9&&!a8)
        {
         JOptionPane.showMessageDialog(this,"Address cannot be empty","Alert",JOptionPane.ERROR_MESSAGE);        
        }
        else if(a1&&a2&&a3&&(a4||a5)&&a6&&a7&&a8&&!a9)
        {
         JOptionPane.showMessageDialog(this,"Invalid email","Alert",JOptionPane.ERROR_MESSAGE);        
        }
        else
        {
         JOptionPane.showMessageDialog(this,"Multiple Fields in Unacceptable Form","Alert",JOptionPane.ERROR_MESSAGE);                 
        }
        if(a1&&a2&&a3&&(a4||a5)&&a6&&a7&&a8&&a9)
        {
            try {
            // 1. Get a connection to database
            myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/rup?characterEncoding=latin1", user, pass);
            //jdbc:mysql://localhost/yourDB;

            // 2. Create a statement
            myStmt = myConn.createStatement();

            
            myStmt.executeUpdate("INSERT INTO `register`(name,email,username,password,age,phone,address) VALUE ('"+c+"','"+email1+"','"+d+"','"+password+"','"+age+"','"+cn+"','"+addr+"')");
            myStmt.executeUpdate("INSERT INTO `login`(username,password) VALUE ('"+d+"','"+password+"')");
            // 4. Process the result set
            //while (myRs.next()) {
                //System.out.println(myRs.getString("DocName") + ", " + myRs.getString("Department"));
            //}
            Introduction I = new Introduction();
            I.setVisible(true);
            dispose();

        } catch (Exception exc) {
            exc.printStackTrace();
        }
            
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Female;
    private javax.swing.ButtonGroup GenderButtonGroup;
    private javax.swing.JRadioButton Male;
    private javax.swing.JTextField Name;
    private javax.swing.JPasswordField Pass1;
    private javax.swing.JPasswordField Pass2;
    private javax.swing.JTextField Username;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
