/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khoj_AI;


import java.io.IOException;
import javax.swing.JOptionPane;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;
import java.awt.Desktop;
import java.util.logging.Level;
import java.util.logging.Logger;





public class Scraper extends javax.swing.JFrame {

    
     static String color = "";
    static String object = "";
    
    String f_final_search = "";
    String j_final_search = "";
    String sp_final_search = "";
    
    Document document;
    int j=0;
    String sortby = "";
    String sortby_sp = "";
    int pageno;
    int temp_page_no;
    int itemno;
    
    
    public Scraper(String ip1, String ip2) {
        
      
        color = ip1;
        object = ip2;

        f_final_search = color +" "+object;
        j_final_search = color +"-"+object;
        sp_final_search = color +"%20"+object;
        
        
        
        
        
        
        
        
        initComponents();
        this.setSize(1050, 670);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label5 = new java.awt.Label();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(68, 67, 74));
        setForeground(new java.awt.Color(204, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        label5.setBackground(new java.awt.Color(68, 67, 74));
        label5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("Copy The Link You Want To Redirect To");
        getContentPane().add(label5);
        label5.setBounds(30, 550, 336, 25);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(430, 550, 605, 26);

        jPanel1.setBackground(new java.awt.Color(68, 67, 74));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Nirmala UI", 0, 60)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Scraper");

        jLabel3.setBackground(new java.awt.Color(68, 67, 74));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Niraj\\Downloads\\drive-download-20191027T114244Z-001\\src\\webscraping\\3df824df-82b8-4072-be29-211263aa2bd8_200x200.png")); // NOI18N

        label2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("You are searching for");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Niraj\\Downloads\\scraper.png")); // NOI18N

        jButton2.setBackground(new java.awt.Color(204, 0, 51));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 0, 51));
        jButton4.setText("Back to Menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addGap(59, 59, 59)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton2)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1050, 190);

        jPanel2.setBackground(new java.awt.Color(33, 32, 38));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setBackground(new java.awt.Color(102, 255, 0));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setText("Get Results");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----", "Relevance", "Popularity", "Price Ascending", "Price Descending" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Parameter For Optimisation");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1023, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(109, 109, 109)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(424, 424, 424))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 190, 1050, 350);

        jPanel3.setBackground(new java.awt.Color(68, 67, 74));

        jButton3.setBackground(new java.awt.Color(102, 255, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Redirect");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(500, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(420, 420, 420))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 520, 1050, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Document document;
        jTextArea1.setText("");
        
        sortby = String.valueOf(jComboBox1.getSelectedItem()).toLowerCase();
        sortby_sp = String.valueOf(jComboBox1.getSelectedItem()).toLowerCase();
        pageno = 1;
       
        
           if(sortby.equalsIgnoreCase("price ascending"))
            {
                sortby = "price_asc";
            }
            else if(sortby.equalsIgnoreCase("price descending"))
            {
                sortby = "price_desc";
            }
        
            if(sortby.equalsIgnoreCase("relevance") || sortby.equalsIgnoreCase("popularity") || sortby.equalsIgnoreCase("price_asc") || sortby.equalsIgnoreCase("price_desc"))
           
               {    
                    j=0;
                    for(pageno=1;pageno<=1;pageno++)
                    {
                        String url = "https://www.flipkart.com/search?q="+f_final_search+"&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&sort="+sortby+"&page="+pageno;
                        try {
                            document = Jsoup.connect(url).get();
                        } catch (IOException ex) {
                            Logger.getLogger(Scraper.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        Elements f_price = document.select("div._1vC4OE");
                        Elements f_item = document.select("a._2mylT6[title]");
                        Elements f_company = document.select("div._2B_pmu");
                        Elements f_links = document.select("a._2mylT6");
                        JOptionPane.showMessageDialog(null,"Fetching Results from Page "+pageno+ " from Flipkart");
                        for(int i=0;i<f_links.size();i++)
                        {
                            jTextArea1.append((++j)+")  "+ " COMPANY : "+f_company.get(i).text()+"   "+" PRODUCT : "+f_item.get(i).text());
                            jTextArea1.append("\n PRICE : "+f_price.get(i).text()+"\n"+" LINK : "+f_links.get(i).attr("abs:href")+"\n"+"---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
                                    + "----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"+"\n\n");
                        }
                        jTextArea1.append("\n\n\n\n");
                        JOptionPane.showMessageDialog(null,"Fetching Results from Page "+pageno+ " from Jabong");
                        url = "https://www.jabong.com/find/"+j_final_search+"?sort="+sortby;
                        try {
                            document = Jsoup.connect(url).userAgent("Opera").get();
                        } catch (IOException ex) {
                            Logger.getLogger(Scraper.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        Elements j_price = document.select("div.col-xxs-6.col-xs-4.col-sm-4.col-md-3.col-lg-3.product-tile.img-responsive[data-discount-price]");
                        Elements j_item = document.select("div.col-xxs-6.col-xs-4.col-sm-4.col-md-3.col-lg-3.product-tile.img-responsive[data-name]");
                        Elements j_company = document.select("div.col-xxs-6.col-xs-4.col-sm-4.col-md-3.col-lg-3.product-tile.img-responsive[data-brand]");
                        Elements j_links = document.select("a.tile-cta.unadjusted");
                        for(int i=0;i<j_links.size();i++)
                        {
                            jTextArea1.append((++j)+")  "+ " COMPANY : "+j_company.get(i).attr("data-brand")+"   "+" PRODUCT : "+j_item.get(i).attr("data-name"));
                            jTextArea1.append("\n PRICE : Rs."+j_price.get(i).attr("data-discount-price")+"\n"+" LINK : "+j_links.get(i).attr("abs:href")+"\n"+"---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
                                    + "----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"+"\n\n");
                        }
                   }
                    
                    if(sortby_sp.equalsIgnoreCase("relevance"))
                    {
                        sortby_sp = "rlvncy";
                    }
                    else if(sortby_sp.equalsIgnoreCase("popularity"))
                    {
                        sortby_sp = "plrty";
                    }
                    else if(sortby_sp.equalsIgnoreCase("price ascending"))
                    {
                        sortby_sp = "plth";
                    }
                    else if(sortby_sp.equalsIgnoreCase("price descending"))
                    {
                        sortby_sp = "phtl";
                    }
                    if(sortby_sp.equalsIgnoreCase("rlvncy") || sortby_sp.equalsIgnoreCase("plrty") || sortby_sp.equalsIgnoreCase("plth") || sortby_sp.equalsIgnoreCase("phtl"))
                    {
                        String url = "https://www.snapdeal.com/search?keyword="+sp_final_search+"&sort="+sortby_sp; //Logger.getLogger(scraper_chatbot.class.getName()).log(Level.SEVERE, null, ex);
                        try {
                            document = Jsoup.connect(url).get();
                        } catch (IOException ex) {
                            Logger.getLogger(Scraper.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        Elements sp_price = document.select("span.lfloat.product-price[display-price]");
                        Elements sp_item = document.select("p.product-title[title]");
                        Elements sp_links = document.select("div.product-tuple-image a");
                        jTextArea1.append("\n\n\n\n");
                        JOptionPane.showMessageDialog(null,"Fetching Results from Page "+1+ " from SnapDeal");
                        for(int i=0;i<sp_item.size();i++)
                        {
                            
                            jTextArea1.append((++j)+" "+" PRODUCT : "+sp_item.get(i).attr("title"));
                            jTextArea1.append("\n PRICE : Rs."+sp_price.get(i).attr("display-price")+"\n"+" LINK : "+sp_links.get(i).attr("abs:href")+"\n"+"---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
                                    + "----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"+"\n\n");
                            
                        }
                     }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Select Parameter For Optimization");
                    
                    }
                }
               
            else
                {
                  JOptionPane.showMessageDialog(null,"Select Parameter For Optimization");
                }
            
           
              
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        label2.setText("Searching for "+f_final_search);  
       
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String my_url = jTextField2.getText();
        
        try
        {
            Desktop.getDesktop().browse(java.net.URI.create(my_url));
        }
        catch( java.io.IOException e)
        {
            System.out.println(e.getMessage());
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Recognizer r = new Recognizer();
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        selection s = new selection();
       s.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scraper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scraper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scraper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scraper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scraper(color,object).setVisible(true);
            }
        });
    }
    
   
    
    
        
      
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private java.awt.Label label2;
    private java.awt.Label label5;
    // End of variables declaration//GEN-END:variables

    private static class jOptionPane {

        public jOptionPane() {
        }
    }
    
}
